apiVersion: v1
kind: Service
metadata:
  name: admin-server
  labels:
    app: admin-server
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app: admin-server