apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  labels:
    app: tracing-server
spec:
  ports:
    - name: http
      port: 9411
      targetPort: 9411
  selector:
    app: tracing-server
  type: ClusterIP
