name: Deploy to AKS

on:
  push:
    branches:
      - main
    paths:
      - "aks-files/**"

jobs:
  deployToAKS:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Azure Variables
        run: |
          echo "AZURE_CLIENT_ID=${{ secrets.SERVICE_PRINCIPAL_ID }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_SECRET=${{ secrets.SERVICE_PRINCIPAL_KEY }}" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV
          echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION }}" >> $GITHUB_ENV
          echo "RESOURCE_GROUP=${{ secrets.AZURE_RESOURCE_GROUP }}" >> $GITHUB_ENV
          echo "AKS_CLUSTER_NAME=${{ secrets.AZURE_AKS_CLUSTER_NAME }}" >> $GITHUB_ENV
        shell: bash

      - name: Login to Azure CLI
        run: |
          az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          az account set --subscription $AZURE_SUBSCRIPTION_ID
        shell: bash

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER_NAME

      - name: Install kubectl
        run: sudo apt-get install -y kubectl

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f ./aks-files
