name: Deploy to AKS

on:
  push:
    branches:
      - main
    paths:
      - "aks-files/**" 

env:
  ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_KEY }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AKS_CLUSTER_NAME: ${{ secrets.AZURE_AKS_CLUSTER_NAME }}

jobs:
  deployToAKS:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
          creds: ${{ secrets.SERVICE_PRINCIPAL_KEY }}

      - name: Set Azure subscription
        run: az account set --subscription ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}

      - name: Install kubectl
        run: sudo apt-get install -y kubectl

      - name: Apply Kubernetes manifests
        run: kubectl apply -f ./aks-files
