name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
    paths:
      - "main.tf"
      - "modules/**"

env:
  ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_KEY }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

jobs:
  terraform-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init (Backend Creation and Remote State)
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform Plan (Backend & Main Resources)
        run: terraform plan -out=tfplan -var "tenant_id=${{ secrets.TENANT_ID }}" -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION }}"  # Planifica todos los recursos

      - name: Terraform Apply (Create or Update Resources)
        run: terraform apply -auto-approve -input=false tfplan