name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
    paths:
      - "main.tf"
      - "backend.tf"
      - "modules/**"

env:
  ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_KEY }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

jobs:
  create-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init for Backend (Creation of Resources)
        run: terraform init -backend=false  # Inicializa Terraform sin backend para crear recursos del backend

      - name: Terraform Apply for Backend (Create Resources)
        run: terraform apply -auto-approve -input=false  # Aplica los recursos del backend (grupo de recursos, almacenamiento, etc.)

  main-deployment:
    runs-on: ubuntu-latest
    needs: create-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init with Remote Backend (Reconfigure)
        run: terraform init -backend=true -reconfigure -force-copy  # Reconfigura el backend remoto y fuerza la copia del estado

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var "tenant_id=${{ secrets.TENANT_ID }}" -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false tfplan